/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package formularios;

import controladorDAO.AlumnoDaoImp;
import controladorDAO.AutorizadoDaoImp;
import entidades.Autorizado;
import entidades.Parentesco;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author juudi
 */
public class frmAutorizado extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmAutorizado
     */
    public frmAutorizado() {
        initComponents();
        configTabla();
        cargaTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtAutorizados = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 255));
        jLabel1.setText("AUTORIZADOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 330, 42));

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
        });
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 750, -1));

        jtAutorizados.setBackground(new java.awt.Color(255, 153, 102));
        jtAutorizados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtAutorizados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtAutorizadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtAutorizados);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 830, 210));

        btnActualizar.setText("Actualizar/Añadir");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 140, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Buscar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configTabla(){ 
    
        String col[]={"ID","DNI","NOMBRE","APELLIDO1","APELLIDO2","PARENTESCO"};
        
        DefaultTableModel modelo=new DefaultTableModel(col,0){
        
              @Override
              public boolean isCellEditable(int row, int column){
                  return false;
              }
        
        };
        
        jtAutorizados.setModel(modelo);
        jtAutorizados.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                
    }
    
    public void cargaTabla(){
        DefaultTableModel modelo=(DefaultTableModel)jtAutorizados.getModel();
        
        AutorizadoDaoImp autControler=AutorizadoDaoImp.getInstance();
        String[] fila=new String[6];
        
        modelo.setNumRows(0);
        try{
            List<Autorizado> lst=autControler.getAll();
            
            for( Autorizado aut :lst){
                fila[0]=""+aut.getId();
                fila[1]=""+aut.getDni();
                fila[2]=""+aut.getNombre();
                fila[3]=""+aut.getApellido1();
                fila[4]="" + aut.getApellido2();
                
                Parentesco parent = aut.getParentesco();
                        
                 
                fila[5]="" + parent.toString();
                modelo.addRow(fila);
            }
            //selecciono la primera fila
           jtAutorizados.setRowSelectionInterval(0,0); 
           
        }catch(Exception e){
            System.out.println("Errorr:"+e.getMessage());
        }
    }
    
    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed

    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            DefaultTableModel modelo=(DefaultTableModel) jtAutorizados.getModel();
            TableRowSorter<TableModel> trSorter = new TableRowSorter<TableModel>(modelo);

            jtAutorizados.setRowSorter(trSorter);

            if (txtBuscar.getText().length()==0) {
                trSorter.setRowFilter(null);
            }else{
                trSorter.setRowFilter(RowFilter.regexFilter(txtBuscar.getText().trim()));
            }

        }
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void jtAutorizadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtAutorizadosMouseClicked
        if (evt.getClickCount()==2){
            try {
                // System.out.println("Doble click.....");
                //Cargar el detalle de un autorizado cuadno se le da doble click
                JDialog frame=new JDialog();
                frame.setTitle("Detalle Autorizado");
                frame.setModal(true);

                jpAutorizadoDetalle panel=new jpAutorizadoDetalle();

                int idseleccion=Integer.parseInt(jtAutorizados.getValueAt(jtAutorizados.getSelectedRow(), 0).toString());

                panel.CargaDetalle(idseleccion);
                panel.frmAut=this;

                frame.getContentPane().add(panel);
                frame.pack();
                frame.setVisible(true);
                
            } catch (Exception ex) {
                Logger.getLogger(jpAlumnoDetalle.class.getName()).log(Level.SEVERE, null, ex);
            }

        }        // TODO add your handling code here:
    }//GEN-LAST:event_jtAutorizadosMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        /*frmAlumnoUpdateAnt frmaluUpdate=new frmAlumnoUpdateAnt();
        frmaluUpdate.setVisible(true);*/
        //Cargar el detalle de un alumno
        try {
            JDialog frame=new JDialog();
            frame.setTitle("Detalle Autorizado");
            frame.setModal(true);

            jpAutorizadoDetalle panel = new jpAutorizadoDetalle();

            int idseleccion=Integer.parseInt(jtAutorizados.getValueAt(jtAutorizados.getSelectedRow(), 0).toString());
            System.out.println("cargando autorizado "+idseleccion);
            panel.CargaDetalle(idseleccion);
            
            //Paso el formulario para poder cargarlo
            panel.frmAut=this;
            
            frame.getContentPane().add(panel);
            frame.pack();
            frame.setVisible(true);

        } catch (Exception ex) {
            Logger.getLogger(frmAutorizado.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("no carga");
        }
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtAutorizados;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
