/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package formularios;

import controladorDAO.AulaDaoImp;
import controladorDAO.CursoDaoImp;
import entidades.Aula;
import entidades.Curso;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author juudi
 */
public class frmAula extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmAula
     */
    public frmAula() {
        initComponents();
        configTabla();
        cargaTabla();
        setCampos();
        txtId.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpcampos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtAulas = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtBuscar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpcampos.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setText("Codigo");

        jLabel3.setText("Descripcion");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualiza");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpcamposLayout = new javax.swing.GroupLayout(jpcampos);
        jpcampos.setLayout(jpcamposLayout);
        jpcamposLayout.setHorizontalGroup(
            jpcamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpcamposLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jpcamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpcamposLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnAgregar)
                        .addGap(37, 37, 37)
                        .addComponent(btnActualizar))
                    .addGroup(jpcamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpcamposLayout.createSequentialGroup()
                            .addGroup(jpcamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addGroup(jpcamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(139, 139, 139))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jpcamposLayout.setVerticalGroup(
            jpcamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpcamposLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jpcamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnActualizar))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jpcampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 290, 220));

        jtAulas.setBackground(new java.awt.Color(102, 204, 255));
        jtAulas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Inicio", "Fin", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtAulas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtAulasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtAulas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 348, 210));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 255));
        jLabel4.setText("AULAS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 160, 42));
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(701, 6, -1, -1));

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
        });
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 170, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Buscar");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configTabla(){
        String col[]={"ID","CODIGO","DESCRIPCION"};
        
        DefaultTableModel modelo=new DefaultTableModel(col,0);
        jtAulas.setModel(modelo);
        jtAulas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    
    }
    
     private void cargaTabla(){
        DefaultTableModel modelo=(DefaultTableModel)jtAulas.getModel();
        
        AulaDaoImp aul=AulaDaoImp.getInstance();
        String[] fila=new String[3];
        
        modelo.setNumRows(0);
        try{
            java.util.List<Aula> lst=aul.getAll();
            
            for(Aula aulas : lst){
                fila[0]=""+aulas.getId();
                fila[1]=""+aulas.getCodigo();
                fila[2]=""+aulas.getDescripcion();
                modelo.addRow(fila);
            }
            //selecciono la primera fila
           jtAulas.setRowSelectionInterval(0,0); 
           
        }catch(Exception e){
            System.out.println("Error:"+e.getMessage());
        }
    }
     
     private Aula getCampos(){
        Aula a=new Aula();
        a.setId(Integer.parseInt(txtId.getText()));
        a.setCodigo(txtCodigo.getText());
        a.setDescripcion(txtDescripcion.getText());
        
        return a;        
    }
    
      private void setCampos(){
        txtId.setText(jtAulas.getValueAt(jtAulas.getSelectedRow(), 0).toString());
        txtCodigo.setText(jtAulas.getValueAt(jtAulas.getSelectedRow(), 1).toString());
        txtDescripcion.setText(jtAulas.getValueAt(jtAulas.getSelectedRow(), 2).toString());
          
    }
      
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        AulaDaoImp aul=AulaDaoImp.getInstance();

        try{
            aul.add(getCampos());
            JOptionPane.showMessageDialog(this, "Aula agregada correctamente");
            cargaTabla();

        }catch(Exception e){
            System.out.println("Error:"+e.getMessage());
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        AulaDaoImp aul=AulaDaoImp.getInstance();

        try{
            aul.update(getCampos());
            JOptionPane.showMessageDialog(this, "Aula actualizado correctamente");
            cargaTabla();
            int fila=jtAulas.getSelectedRow();
            jtAulas.setRowSelectionInterval(fila,fila);

        }catch(Exception e){
            System.out.println("Error:"+e.getMessage());
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void jtAulasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtAulasMouseClicked
        // TODO add your handling code here:
        setCampos();
    }//GEN-LAST:event_jtAulasMouseClicked

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            DefaultTableModel modelo=(DefaultTableModel) jtAulas.getModel();
            TableRowSorter<TableModel> trSorter = new TableRowSorter<TableModel>(modelo);

            jtAulas.setRowSorter(trSorter);

            if (txtBuscar.getText().length()==0) {
                trSorter.setRowFilter(null);
            }else{

                trSorter.setRowFilter(RowFilter.regexFilter(txtBuscar.getText().trim()));
            }

        }
    }//GEN-LAST:event_txtBuscarKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpcampos;
    private javax.swing.JTable jtAulas;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
