/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package formularios;

import javax.swing.JInternalFrame;

/**
 *
 * @author juudi
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEscritorio = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        optmAlumno = new javax.swing.JMenuItem();
        optmAula = new javax.swing.JMenuItem();
        optmCurso = new javax.swing.JMenuItem();
        optmCurAca = new javax.swing.JMenuItem();
        optmUnidad = new javax.swing.JMenuItem();
        optmPersonal = new javax.swing.JMenuItem();
        optmAutorizados = new javax.swing.JMenuItem();
        optmMatricula = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Entidades");

        optmAlumno.setMnemonic('o');
        optmAlumno.setText("Alumnos");
        optmAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmAlumnoActionPerformed(evt);
            }
        });
        fileMenu.add(optmAlumno);

        optmAula.setMnemonic('a');
        optmAula.setText("Aulas");
        optmAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmAulaActionPerformed(evt);
            }
        });
        fileMenu.add(optmAula);

        optmCurso.setMnemonic('x');
        optmCurso.setText("Cursos");
        optmCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmCursoActionPerformed(evt);
            }
        });
        fileMenu.add(optmCurso);

        optmCurAca.setText("Cursos Academicos");
        optmCurAca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmCurAcaActionPerformed(evt);
            }
        });
        fileMenu.add(optmCurAca);

        optmUnidad.setText("Unidades");
        optmUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmUnidadActionPerformed(evt);
            }
        });
        fileMenu.add(optmUnidad);

        optmPersonal.setText("Personal");
        optmPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmPersonalActionPerformed(evt);
            }
        });
        fileMenu.add(optmPersonal);

        optmAutorizados.setText("Autorizados");
        optmAutorizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmAutorizadosActionPerformed(evt);
            }
        });
        fileMenu.add(optmAutorizados);

        optmMatricula.setText("Matriculas");
        optmMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmMatriculaActionPerformed(evt);
            }
        });
        fileMenu.add(optmMatricula);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optmCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmCursoActionPerformed
         frmCurso frmcur=null;
       
       if (!existeFormulario(frmcur)){
            frmcur=new frmCurso();
            pnlEscritorio.add(frmcur);
            frmcur.show();   
           
       }
    }//GEN-LAST:event_optmCursoActionPerformed

    private void optmAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmAlumnoActionPerformed
       
       frmAlumno frmalum=null;
       
       if (!existeFormulario(frmalum)){
            frmalum=new frmAlumno();
            pnlEscritorio.add(frmalum);
            frmalum.show();      
       }
    }//GEN-LAST:event_optmAlumnoActionPerformed

    private void optmAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmAulaActionPerformed
        frmAula frmaul=null;
       
       if (!existeFormulario(frmaul)){
            frmaul=new frmAula();
            pnlEscritorio.add(frmaul);
            frmaul.show();      
       }
    }//GEN-LAST:event_optmAulaActionPerformed

    private void optmCurAcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmCurAcaActionPerformed
       frmCursoAcademico frmaac=null;
       
       if (!existeFormulario(frmaac)){
            frmaac=new frmCursoAcademico();
            pnlEscritorio.add(frmaac);
            frmaac.show();      
       }
       
    }//GEN-LAST:event_optmCurAcaActionPerformed

    private void optmUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmUnidadActionPerformed
        
        frmUnidad frmuni=null;
       
       if (!existeFormulario(frmuni)){
            frmuni=new frmUnidad();
            pnlEscritorio.add(frmuni);
            frmuni.show();      
       }
    }//GEN-LAST:event_optmUnidadActionPerformed

    private void optmPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmPersonalActionPerformed
       frmPersonal frmp=null;
       
       if (!existeFormulario(frmp)){
            frmp=new frmPersonal();
            pnlEscritorio.add(frmp);
            frmp.show();      
       }
    }//GEN-LAST:event_optmPersonalActionPerformed

    private void optmAutorizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmAutorizadosActionPerformed
       frmAutorizado frmaut=null;
       
       if (!existeFormulario(frmaut)){
            frmaut=new frmAutorizado();
            pnlEscritorio.add(frmaut);
            frmaut.show();      
       }
    }//GEN-LAST:event_optmAutorizadosActionPerformed

    private void optmMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmMatriculaActionPerformed
       frmMatricula frmM=null;
       
       if (!existeFormulario(frmM)){
            frmM=new frmMatricula();
            pnlEscritorio.add(frmM);
            frmM.show();      
       }
    }//GEN-LAST:event_optmMatriculaActionPerformed

    //METODO PARA QUE SOLO ME ABRA UN FORMULARIO
       private boolean existeFormulario(Object object){
    
        JInternalFrame[] frmcargados=pnlEscritorio.getAllFrames();
        
        for(int i=0;i<frmcargados.length;i++){ 
            if (frmcargados[i].getClass()==object.getClass()){
                return true;
            }
            
        }
        return false;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem optmAlumno;
    private javax.swing.JMenuItem optmAula;
    private javax.swing.JMenuItem optmAutorizados;
    private javax.swing.JMenuItem optmCurAca;
    private javax.swing.JMenuItem optmCurso;
    private javax.swing.JMenuItem optmMatricula;
    private javax.swing.JMenuItem optmPersonal;
    private javax.swing.JMenuItem optmUnidad;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JDesktopPane pnlEscritorio;
    // End of variables declaration//GEN-END:variables

}
