/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package formularios;

import controladorDAO.AlumnoDaoImp;
import entidades.Alumno;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author juudi
 */
public class jpAlumnoDetalle extends javax.swing.JPanel {

    public int id;
    public frmAlumno frmAlu;
    /**
     * Creates new form jpAlumnoDetalle
     */
    public jpAlumnoDetalle() throws SQLException {
        initComponents();
        
    }

    public void CargaDetalle(int id){
        this.id=id;
        lblId.setText(""+id);
        setCampos();
        
        //llamar al controlador para cargar el alumno con método getById
    }
    
    private void setCampos() {
    
        AlumnoDaoImp a = AlumnoDaoImp.getInstance();
        try{
            Alumno alum=a.getById(this.id);
            
            txtDni.setText(""+alum.getDni());
            txtNombre.setText(""+alum.getNombre());
            txtAp1.setText(""+alum.getApellido1());
            txtAp2.setText(""+alum.getApellido2());
            txtFNac.setText(""+alum.getFnacimiento().toString());
            txtTelf.setText(""+alum.getTelefono());
            txtEmail.setText(""+alum.getEmail());
            txtDir.setText(""+alum.getDireccion());
            txtCp.setText(""+alum.getCp());
            txtPobla.setText(""+alum.getPoblacion());
            txtProvincia.setText(""+alum.getProvincia());
        }catch(Exception e){
                System.out.println("Erro cargando alumno: "+e.getMessage());
        }
    }
     
     private Alumno getCampos(){
         try {
            Alumno alum=new Alumno();
            //SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/dd");
            //Date d=formato.parse(txtFNac.getText());
            
            alum.setId(id);
            alum.setDni(""+txtDni.getText());
            alum.setNombre(""+txtNombre.getText());
            alum.setApellido1(""+txtAp1.getText());
            alum.setApellido2(""+txtAp2.getText());
            
             if (!(txtFNac.getText()).equals("")) {
                 System.out.println(txtFNac.getText());
                alum.setFnacimiento(Date.valueOf(txtFNac.getText())); 
                 
             }else{
                 alum.setFnacimiento(null);
             }
            
            alum.setTelefono(""+txtTelf.getText());
            alum.setEmail(""+txtEmail.getText());
            alum.setDireccion(""+txtDir.getText());
            alum.setCp(""+txtCp.getText());
            alum.setPoblacion(""+txtPobla.getText());

            return alum;
            
         } catch (Exception e) {
             System.out.println(""+e.getMessage());
         }
         return  null;
 }
     
              
    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAp1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAp2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFNac = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTelf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDir = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPobla = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtProvincia = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        btnRestablecer = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 255));
        jLabel1.setText(" ALUMNOS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, 42));

        jLabel2.setText("DNI");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 70, 20));
        add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 90, 30));

        jLabel3.setText("Nombre");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 70, 20));
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 79, 30));

        jLabel4.setText("Apellido1");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, 20));
        add(txtAp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 70, 30));

        jLabel5.setText("Apellido2");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, 20));
        add(txtAp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 70, 30));

        jLabel6.setText("Fecha Nacimiento");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, 20));
        add(txtFNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 100, 30));

        jLabel7.setText("Teléfono");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, 20));
        add(txtTelf, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 90, 30));

        jLabel8.setText("Email");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, 20));
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 110, 30));

        jLabel9.setText("Direccion");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, 20));
        add(txtDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 120, 30));

        jLabel10.setText("Cp");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, 20));
        add(txtCp, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 70, 30));

        jLabel11.setText("Poblacion");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, 20));
        add(txtPobla, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 70, 30));

        jLabel12.setText("Provincia");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, -1, 20));
        add(txtProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 70, 30));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, -1, -1));
        add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 20, 60, 40));

        btnRestablecer.setText("Restablecer datos");
        btnRestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestablecerActionPerformed(evt);
            }
        });
        add(btnRestablecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setForeground(new java.awt.Color(153, 255, 204));
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 620, 270));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        AlumnoDaoImp alum=AlumnoDaoImp.getInstance();
        
        if ((alum.Existe(txtDni.getText()))==0) {
            
            try{
                alum.add(getCampos());
                JOptionPane.showMessageDialog(this, "Alumno añadido correctamente");
                frmAlu.cargaTabla();

            }catch(Exception e){
                System.out.println(txtDni.getText());
                System.out.println("Error añadir:"+e.getMessage());
            }
        }else{
                try{
                    alum.update(getCampos());
                    JOptionPane.showMessageDialog(this, "Alumno actualizado correctamente");
                    frmAlu.cargaTabla();
            
                }catch(Exception e){
                    System.out.println("Error update:"+e.getMessage());
                }
        }
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnRestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecerActionPerformed
          try{
            
            txtDni.setText("");
            txtNombre.setText("");
            txtAp1.setText("");
            txtAp2.setText("");
            txtFNac.setText("");
            txtTelf.setText("");
            txtEmail.setText("");
            txtDir.setText("");
            txtCp.setText("");
            txtPobla.setText("");
            txtProvincia.setText("");
        }catch(Exception e){
                System.out.println("Erro cargando alumno: "+e.getMessage());
        }
    }//GEN-LAST:event_btnRestablecerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnRestablecer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblId;
    private javax.swing.JTextField txtAp1;
    private javax.swing.JTextField txtAp2;
    private javax.swing.JTextField txtCp;
    private javax.swing.JTextField txtDir;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFNac;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPobla;
    private javax.swing.JTextField txtProvincia;
    private javax.swing.JTextField txtTelf;
    // End of variables declaration//GEN-END:variables
}
