/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package formularios;

import controladorDAO.AutorizadoDaoImp;
import entidades.Autorizado;
import entidades.Parentesco;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JComboBox;

/**
 *
 * @author juudi
 */
public class jpAutorizadoDetalle extends javax.swing.JPanel {

    public int id;
    public frmAutorizado frmAut;
    
    
    /**
     * Creates new form jpAutorizadoDetalle
     */
    public jpAutorizadoDetalle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAp1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAp2 = new javax.swing.JTextField();
        btnAceptar1 = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        btnRestablecer = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cmbParentesco = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();

        jMenuItem1.setText("jMenuItem1");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 255));
        jLabel1.setText("AUTORIZADOS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, 42));

        jLabel2.setText("DNI");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 70, 20));
        add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 90, 30));

        jLabel3.setText("Nombre");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 70, 20));
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 79, 30));

        jLabel4.setText("Apellido1");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, 20));
        add(txtAp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 70, 30));

        jLabel5.setText("Apellido2");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, 20));
        add(txtAp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 70, 30));

        btnAceptar1.setText("Aceptar");
        btnAceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar1ActionPerformed(evt);
            }
        });
        add(btnAceptar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, -1, -1));
        add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 20, 60, 40));

        btnRestablecer.setText("Restablecer datos");
        btnRestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestablecerActionPerformed(evt);
            }
        });
        add(btnRestablecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        jLabel6.setText("Parentesco");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 70, 20));

        cmbParentesco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TUTOR1", "TUTOR2", "OTROS" }));
        cmbParentesco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbParentescoActionPerformed(evt);
            }
        });
        add(cmbParentesco, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 470, 230));
    }// </editor-fold>//GEN-END:initComponents

    public void CargaDetalle(int id){
        this.id=id;
        lblId.setText(""+id);
        setCampos();
        
        //llamar al controlador para cargar el alumno con método getById
    }
     
    private void setCampos() {
        AutorizadoDaoImp autDaoImp = AutorizadoDaoImp.getInstance();
        try{
            Autorizado aut=autDaoImp.getById(this.id);
            
            txtDni.setText(""+aut.getDni());
            txtNombre.setText(""+aut.getNombre());
            txtAp1.setText(""+aut.getApellido1());
            txtAp2.setText(""+aut.getApellido2());
            cmbParentesco.setSelectedItem(aut.getParentesco().toString());
            
      
        }catch(Exception e){
                System.out.println("Erro cargando autorizado: "+e.getMessage());
        }
    }
    
    private Autorizado getCampos(){
         try {
            Autorizado aut=new Autorizado();
            
            aut.setId(id);
             
            aut.setDni(""+txtDni.getText());
            aut.setNombre(""+txtNombre.getText());
            aut.setApellido1(""+txtAp1.getText());
            aut.setApellido2(""+txtAp2.getText());
            
             
            String selectedItem = (String) cmbParentesco.getSelectedItem();
            Parentesco parentesco = null;

            // Realizar la conversión manual del valor seleccionado a Parentesco
            if (selectedItem.equals("TUTOR1")) {
                parentesco = Parentesco.TUTOR1;
            } else if (selectedItem.equals("TUTOR2")) {
                parentesco = Parentesco.TUTOR2;
            } else if (selectedItem.equals("OTROS")) {
                parentesco = Parentesco.OTROS;
            }

            aut.setParentesco(parentesco);

            return aut;
            
         } catch (Exception e) {
             System.out.println("Error al obtener los campos: " + e.getMessage());
      
             return null;
         }
         
    }
    
    
    private void btnAceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar1ActionPerformed
        AutorizadoDaoImp aut=AutorizadoDaoImp.getInstance();
        

        if ((aut.Existe(txtDni.getText()))==0) {

            try{
                aut.add(getCampos());
                JOptionPane.showMessageDialog(this, "Autorizado añadido correctamente");
                frmAut.cargaTabla();

            }catch(Exception e){
                System.out.println(txtDni.getText());
                System.out.println("Error añadir:"+e.getMessage());
            }
        }else{
            try{
                aut.update(getCampos());
                JOptionPane.showMessageDialog(this, "Autorizado actualizado correctamente");
                frmAut.cargaTabla();

            }catch(Exception e){
                System.out.println("Error update:"+e.getMessage());
            }
        }

    }//GEN-LAST:event_btnAceptar1ActionPerformed

    
    private void btnRestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecerActionPerformed
        try{

            txtDni.setText("");
            txtNombre.setText("");
            txtAp1.setText("");
            txtAp2.setText("");
          
        }catch(Exception e){
            System.out.println("Erro cargando autorizado: "+e.getMessage());
        }
    }//GEN-LAST:event_btnRestablecerActionPerformed

    
    private void cmbParentescoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbParentescoActionPerformed
        /*DefaultComboBoxModel<Parentesco> model = (DefaultComboBoxModel<Parentesco>) cmbParentesco.getModel();
        model.addElement(Parentesco.TUTOR1);
        model.addElement(Parentesco.TUTOR2);
        model.addElement(Parentesco.OTROS);*/
    }//GEN-LAST:event_cmbParentescoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar1;
    private javax.swing.JButton btnRestablecer;
    private javax.swing.JComboBox<String> cmbParentesco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblId;
    private javax.swing.JTextField txtAp1;
    private javax.swing.JTextField txtAp2;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
