/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package formularios;

import BD.MyDataSource;
import controladorDAO.AulaDaoImp;
import controladorDAO.MatriculaDaoImp;
import controladorDAO.UnidadDaoImp;
import entidades.Alumno;
import entidades.Aula;
import entidades.Unidad;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author juudi
 */
public class jpMatriculaDetalle extends javax.swing.JPanel {
    public int id;
    public frmMatricula frm;
    public int idAlum;
    
    DefaultListModel<String> alumnosNColeccion;
    DefaultListModel<String> alumnosColeccion;
    /**
     * Creates new form frmMatriculaDetalle
     */
    public jpMatriculaDetalle() {
        initComponents();
        generarcmbUnidades();
        generarListNMatricula();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListNoMat = new javax.swing.JList<>();
        jbPasar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListMat = new javax.swing.JList<>();
        btnAceptar = new javax.swing.JButton();
        cmbUnidades = new javax.swing.JComboBox<>();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 255));
        jLabel1.setText("MATRICULAR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, 42));
        jPanel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 20, 60, 40));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setForeground(new java.awt.Color(153, 153, 255));

        jListNoMat.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListNoMat);

        jPanel2.add(jScrollPane2);

        jbPasar.setText(">");
        jbPasar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPasarActionPerformed(evt);
            }
        });
        jPanel2.add(jbPasar);

        jListMat.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "hola" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListMat);

        jPanel2.add(jScrollPane1);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAceptar);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 480, 320));

        cmbUnidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbUnidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        
        
        
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void jbPasarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPasarActionPerformed
     
        if (jListNoMat.getSelectedValuesList() != null){
            for(String a : jListNoMat.getSelectedValuesList()){
                alumnosColeccion.addElement(a);
                alumnosNColeccion.removeElement(a);
            }
        }
    }//GEN-LAST:event_jbPasarActionPerformed


 
    
    private void generarListNMatricula(){
        MatriculaDaoImp alum = MatriculaDaoImp.getInstance();
        
        try {
            List<Alumno> lst=alum.consultaAlumNMatricula();
            alumnosNColeccion = new DefaultListModel<String>();
            jListNoMat.setModel(alumnosNColeccion);
            
            alumnosColeccion = new DefaultListModel<String>();
            jListMat.setModel(alumnosColeccion);
           
            for(Alumno a : lst){
                  alumnosNColeccion.addElement(a.getNombre());
                //alumnosNColeccion.add(a.getId(), a.getNombre());
            }
            
           
        } catch (Exception e) {
            System.out.println("Error"+e.getMessage());
        
        }
        
    }
    
   private void generarcmbUnidades(){
        cmbUnidades.removeAllItems();
        MatriculaDaoImp unidad = MatriculaDaoImp.getInstance();
        
        try {
            List<Unidad> lst=unidad.consultaUnidades();
            DefaultListModel<String> unidadColeccion = new DefaultListModel<String>();
            jListNoMat.setModel(unidadColeccion);
            
            for(Unidad u : lst){
                cmbUnidades.addItem(u.getCodigo());
            }
            
           
        } catch (Exception e) {
            System.out.println("Error"+e.getMessage());
        
        }
    }
    
  /*   private void generarcmbUnidades(){
        cmbUnidades.removeAllItems();
        UnidadDaoImp controladorUni = UnidadDaoImp.getInstance();
        
        try {
            List<Unidad> lst=controladorUni.getAll();
            
            for(Unidad u : lst){
                cmbUnidades.addItem(u.getCodigo());
            }
            
           
        } catch (Exception e) {
            System.out.println("Error"+e.getMessage());
        
        }
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JComboBox<String> cmbUnidades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jListMat;
    private javax.swing.JList<String> jListNoMat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbPasar;
    private javax.swing.JLabel lblId;
    // End of variables declaration//GEN-END:variables
}
