/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package formularios;


import controladorDAO.AulaDaoImp;
import controladorDAO.CursoDaoImp;
import controladorDAO.PersonalDaoImp;
import controladorDAO.UnidadDaoImp;
import entidades.Aula;
import entidades.Curso;
import entidades.Personal;
import entidades.Unidad;
import java.util.Enumeration;
import java.util.HashSet;
import java.util.List;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author juudi
 */
public class jpUnidadDetalle extends javax.swing.JPanel {

    public int id;
    public frmUnidad frmUni;
    
    /**
     * Creates new form jpUnidadDetalle
     */
    public jpUnidadDetalle() {
        initComponents();
        generarcmbAula();
        generarcmbTutor();
        generarcmbCurso();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnRestablecer = new javax.swing.JButton();
        btnAceptar1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cmbCurso = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtObservaciones = new javax.swing.JTextField();
        cmbTutor = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbAula = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtIdTutor = new javax.swing.JLabel();
        txtIdCurso = new javax.swing.JLabel();
        txtIdAula = new javax.swing.JLabel();
        button2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 255));
        jLabel1.setText("UNIDAD");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, 42));

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        btnRestablecer.setText("Restablecer datos");
        btnRestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestablecerActionPerformed(evt);
            }
        });

        btnAceptar1.setText("Aceptar");
        btnAceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Curso");

        cmbCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCursoActionPerformed(evt);
            }
        });

        jLabel4.setText("Observaciones");

        cmbTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTutorActionPerformed(evt);
            }
        });

        jLabel7.setText("Tutor");

        jLabel2.setText("Codigo");

        jLabel3.setText("Nombre");

        cmbAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAulaActionPerformed(evt);
            }
        });

        jLabel8.setText("Aula");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRestablecer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAceptar1)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbAula, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 51, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(52, 52, 52))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(cmbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbAula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRestablecer)
                    .addComponent(btnAceptar1))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 530, 300));
        add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 60, 40));

        txtIdTutor.setText("jLabel5");

        txtIdCurso.setText("jLabel9");

        txtIdAula.setText("jLabel10");

        button2.setText("jButton1");
        button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdAula)
                    .addComponent(txtIdCurso)
                    .addComponent(txtIdTutor))
                .addContainerGap(662, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button2)
                .addGap(261, 261, 261))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(txtIdTutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdAula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 332, Short.MAX_VALUE)
                .addComponent(button2)
                .addGap(38, 38, 38))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 500));
    }// </editor-fold>//GEN-END:initComponents

     public void CargaDetalle(int id){
        this.id=id;
        lblId.setText(""+id);
        setCampos();
        
    }
     
    private void setCampos() {
        UnidadDaoImp uniDaoImp = UnidadDaoImp.getInstance();
        try{
            Unidad uni=uniDaoImp.getById(this.id);
            
            txtCodigo.setText(""+uni.getCodigo());
            txtNombre.setText(""+uni.getNombre());
            txtObservaciones.setText(""+uni.getObservaciones());
        
            cmbTutor.setSelectedItem(uni.getIdtutor());
            System.out.println(uni.getIdtutor());
            cmbAula.setSelectedItem(uni.getIdaula());
            cmbCurso.setSelectedItem(uni.getIdcurso());
            
            txtIdAula.setText(uni.getIdaula()+"");
            txtIdCurso.setText(uni.getIdcurso()+"");
            txtIdTutor.setText(uni.getIdtutor()+"");
            
      
        }catch(Exception e){
                System.out.println("Error cargando unidad: "+e.getMessage());
        }
    }
    
    private Unidad getCampos(){
         try {
            Unidad uni=new Unidad();
            AulaDaoImp controladorAula = AulaDaoImp.getInstance();
            
            uni.setId(id);
             
            uni.setCodigo(""+txtCodigo.getText());
            uni.setNombre(""+txtNombre.getText());
            uni.setObservaciones(""+txtObservaciones.getText());
            
           /* uni.setIdaula(Integer.parseInt(txtIdAula.getText()));
            uni.setIdcurso(Integer.parseInt(txtIdCurso.getText()));
            uni.setIdtutor(Integer.parseInt(txtIdTutor.getText()));
            
           
            uni.setIdaula(controladorAula.getByNom(cmbAula.getSelectedItem().toString()));
             System.out.println("id "+cmbAula.getSelectedItem().toString()+ "es " + controladorAula.getByNom(cmbAula.getSelectedItem().toString()));
            */
            String nombreAula = cmbAula.getSelectedItem().toString();
            int idAula = controladorAula.getByNom(nombreAula);
            uni.setIdaula(idAula);

            
            return uni;
            
         } catch (Exception e) {
             System.out.println("Error al obtener los campos: " + e.getMessage());
      
             return null;
         }
         
    }
    private void generarcmbAula(){
        cmbAula.removeAllItems();
        AulaDaoImp controladorAula = AulaDaoImp.getInstance();
        
        try {
            List<Aula> lst=controladorAula.getAll();
            
            for(Aula a : lst){
                cmbAula.addItem(a.getDescripcion());
            }
            
           
        } catch (Exception e) {
            System.out.println("Error"+e.getMessage());
        
        }
    }
    
    private void generarcmbCurso(){
        cmbCurso.removeAllItems();
        CursoDaoImp controladorCurso = CursoDaoImp.getInstance();
        
        try {
            List<Curso> lst=controladorCurso.getAll();
            
            for(Curso c : lst){
                cmbCurso.addItem(c.getNombre());
            }
            
           
        } catch (Exception e) {
            System.out.println("Error"+e.getMessage());
        
        }
    }
    
    private void generarcmbTutor(){
        cmbTutor.removeAllItems();
        PersonalDaoImp controladorTutor = PersonalDaoImp.getInstance();
        
        try {
            List<Personal> lst=controladorTutor.getAll();
            
            for(Personal p : lst){
                cmbTutor.addItem(p.getNombre()+" " +p.getApellido1()+ " " + p.getApellido2());
            }
            
           
        } catch (Exception e) {
            System.out.println("Error"+e.getMessage());
        
        }
    }
    
    private void cmbAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAulaActionPerformed
        AulaDaoImp controladorAula = AulaDaoImp.getInstance();
        
        try {
            List<Aula> lst=controladorAula.getAll();
            
            for(Aula a : lst){
                cmbAula.addItem(a.getDescripcion());
                //System.out.println(a.getDescripcion());
                //System.out.println("Número de aulas obtenidas: " + lst.size());
            }
            
           
        } catch (Exception e) {
            System.out.println("Error"+e.getMessage());
        
        }
    }//GEN-LAST:event_cmbAulaActionPerformed


    private void cmbTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTutorActionPerformed

    private void cmbCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCursoActionPerformed
        
    }//GEN-LAST:event_cmbCursoActionPerformed

    private void btnAceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar1ActionPerformed
        UnidadDaoImp uni=UnidadDaoImp.getInstance();

        if ((uni.Existe(lblId.getText())==0)) {

            try{
                uni.add(getCampos());
                JOptionPane.showMessageDialog(this, "Unidad añadida correctamente");
                frmUni.cargaTabla();

            }catch(Exception e){
                System.out.println(lblId.getText());
                System.out.println("Error añadir:"+e.getMessage());
            }
        }else{
            try{
                uni.update(getCampos());
                JOptionPane.showMessageDialog(this, "Unidad añadida correctamente");
                frmUni.cargaTabla();

            }catch(Exception e){
                System.out.println("Error update:"+e.getMessage());
            }
        }
    }//GEN-LAST:event_btnAceptar1ActionPerformed

    private void btnRestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecerActionPerformed
        try{

            txtCodigo.setText("");
            txtNombre.setText("");
            txtObservaciones.setText("");

        }catch(Exception e){
            System.out.println("Erro cargando uni: "+e.getMessage());
        }
    }//GEN-LAST:event_btnRestablecerActionPerformed

    private void button2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MouseClicked
        System.out.println(cmbAula.getSelectedItem().toString());
    }//GEN-LAST:event_button2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar1;
    private javax.swing.JButton btnRestablecer;
    private javax.swing.JButton button2;
    private javax.swing.JComboBox<String> cmbAula;
    private javax.swing.JComboBox<String> cmbCurso;
    private javax.swing.JComboBox<String> cmbTutor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblId;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JLabel txtIdAula;
    private javax.swing.JLabel txtIdCurso;
    private javax.swing.JLabel txtIdTutor;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
